name: Upload to Nexus Manually

on:
  pull_request:
    types: [closed]  # Run when PR is closed

jobs:
  nexus-upload:
    if: github.event.pull_request.merged == true  # Only run if the PR is merged
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Create ZIP of the script folder
        run: |
          zip -r script.zip ./script

      - name: Append timestamp to ZIP file
        run: |
          mv script.zip "script_$(date +%Y%m%d%H%M%S).zip"

      - name: Upload to Nexus
        run: |
          curl -v -u ${{ secrets.NEXUS_USERNAME }}:${{ secrets.NEXUS_PASSWORD }} --upload-file "script_$(date +%Y%m%d%H%M%S).zip" http://13.201.10.253:8081/repository/docker_hardening_script/



